# Generated by Django 3.0.3 on 2020-02-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateslot',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_calendar.Candidate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_calendar.Candidate'),
        ),
        migrations.AlterField(
            model_name='interviewerslot',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_calendar.Interviewer'),
        ),
        migrations.AlterField(
            model_name='interviewinterviewer',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_calendar.Interview'),
        ),
        migrations.AlterField(
            model_name='interviewinterviewer',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_calendar.Interviewer'),
        ),
    ]
