# Generated by Django 3.0.3 on 2020-02-19 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_calendar', '0002_auto_20200218_1914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='candidateslot',
            unique_together={('start_date', 'end_date', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('candidate', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='interviewer',
            unique_together={('name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='interviewerslot',
            unique_together={('start_date', 'end_date', 'interviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='interviewinterviewer',
            unique_together={('interview', 'interviewer')},
        ),
    ]
